CREATE VIEW VIEW_1 AS
SELECT CNAME
FROM CUSTOMER
WHERE RATING = (SELECT MAX(RATING)
FROM CUSTOMER);

CREATE VIEW VIEW_2 AS
SELECT COUNT(SNAME),CITY
FROM SALESPEOPLE
GROUP BY CITY;

CREATE VIEW VIEW_3 AS
SELECT "Total Orders","Average",SNAME
FROM SALESPEOPLE
INNER JOIN
    (SELECT COUNT(SNUM) AS "Total Orders",AVG(AMT) as "Average", SNUM
	FROM ORDERS
	GROUP BY SNUM) E1
ON SALESPEOPLE.SNUM = E1.SNUM;

CREATE VIEW VIEW_4 AS
SELECT "Count",SNAME
FROM SALESPEOPLE
INNER JOIN
    (SELECT COUNT(CUSTOMER.CNUM) AS "Count",SALESPEOPLE.SNUM
	FROM SALESPEOPLE,CUSTOMER,ORDERS
	WHERE SALESPEOPLE.SNUM=ORDERS.SNUM
	AND CUSTOMER.CNUM =ORDERS.CNUM
	GROUP BY SALESPEOPLE.SNUM) e1
ON SALESPEOPLE.SNUM = e1.SNUM
WHERE "Count" > 1;

CREATE VIEW Salespeople_Customer_Orders AS
SELECT SALESPEOPLE.SNAME AS "SalespeopleName", CUSTOMER.CNUM AS "CustomerName", ONUM AS "OrderNumber"
FROM SALESPEOPLE,CUSTOMER,ORDERS
WHERE SALESPEOPLE.SNUM = ORDERS.SNUM
AND CUSTOMER.CNUM = ORDERS.CNUM;

CREATE VIEW SalespeopleCommision AS
SELECT SNUM,COMM
FROM SALESPEOPLE
WHERE COMM BETWEEN 1000 AND 2000;

