# create GUI to prepare scientific calculator

from tkinter import *

root = Tk()
root.title('Scientific Calculator')

equation = StringVar(value='0')
input = Entry(root, textvariable=equation,bd=10, width=25, font=("Lucida Console",22), justify=RIGHT)
input.grid(row=0, column=0, columnspan=5)

btn_combo = Button(root, text="nCr", height=2, width=8).grid(row=1, column=0)
btn_permu = Button(root, text="nPr", height=2, width=8).grid(row=1, column=1)
btn_mod = Button(root, text="Mod", height=2, width=8).grid(row=1, column=2)
btn_ce = Button(root, text="CE", height=2, width=8).grid(row=1, column=3)
btn_ac = Button(root, text="AC", height=2, width=8).grid(row=1, column=4)
btn_fact = Button(root, text="x!", height=2, width=8).grid(row=2, column=0)
btn_deg = Button(root, text="deg", height=2, width=8).grid(row=2, column=1)
btn_random = Button(root, text="Ran", height=2, width=8).grid(row=2, column=2)
btn_log10 = Button(root, text="log", height=2, width=8).grid(row=2, column=3)
btn_loge = Button(root, text="ln", height=2, width=8).grid(row=2, column=4)
btn_root = Button(root, text="√", height=2, width=8).grid(row=3, column=0)
btn_power = Button(root, text='x\u02b8', height=2, width=8).grid(row=3, column=1)
btn_reciprocal = Button(root, text='x\u207b\u00b9', height=2, width=8).grid(row=3, column=2)
btn_div = Button(root, text="/", height=2, width=8).grid(row=3, column=3)
btn_sin = Button(root, text="sin", height=2, width=8).grid(row=3, column=4)
btn_7 = Button(root, text="7", height=2, width=8).grid(row=4, column=0)
btn_8 = Button(root, text="8", height=2, width=8).grid(row=4, column=1)
btn_9 = Button(root, text="9", height=2, width=8).grid(row=4, column=2)
btn_mult = Button(root, text="x", height=2, width=8).grid(row=4, column=3)
btn_cos = Button(root, text="cos", height=2, width=8).grid(row=4, column=4)
btn_4 = Button(root, text="4", height=2, width=8).grid(row=5, column=0)
btn_5 = Button(root, text="5", height=2, width=8).grid(row=5, column=1)
btn_6 = Button(root, text="6", height=2, width=8).grid(row=5, column=2)
btn_sub = Button(root, text="-", height=2, width=8).grid(row=5, column=3)
btn_tan = Button(root, text="tan", height=2, width=8).grid(row=5, column=4)
btn_1 = Button(root, text="1", height=2, width=8).grid(row=6, column=0)
btn_2 = Button(root, text="2", height=2, width=8).grid(row=6, column=1)
btn_3 = Button(root, text="3", height=2, width=8).grid(row=6, column=2)
btn_add = Button(root, text="+", height=2, width=8).grid(row=6, column=3)
btn_pi = Button(root, text="π", height=2, width=8).grid(row=6, column=4)
btn_sign = Button(root, text="+/-", height=2, width=8).grid(row=7, column=0)
btn_0 = Button(root, text="0", height=2, width=8).grid(row=7, column=1)
btn_point = Button(root, text=".", height=2, width=8).grid(row=7, column=2)
btn_e = Button(root, text="e", height=2, width=8).grid(row=7, column=3)
btn_equals = Button(root, text="=", height=2, width=8).grid(row=7, column=4)

root.mainloop()