SELECT PNO,PNAME 
FROM PARTS
WHERE PRICE < 20;

SELECT PARTS.PNO 
FROM PARTS,ODETAILS
WHERE PARTS.PNO=ODETAILS.PNO;

SELECT *
FROM CUSTOMERS
WHERE CNAME LIKE 'S%';

SELECT ONO,CNAME
FROM ORDERS,CUSTOMERS
WHERE CUSTOMERS.CNO=ORDERS.CNO
AND SHIPPED IS NULL;

SELECT CNAME, ENAME
FROM CUSTOMERS,EMPLOYEES,ORDERS
WHERE ORDERS.CNO = CUSTOMERS.CNO
AND ORDERS.ENO=EMPLOYEES.ENO;

SELECT ENAME
FROM EMPLOYEES
ORDER BY HDATE ASC
FETCH FIRST 1 ROWS ONLY;

SELECT PNO,PNAME,PRICE
FROM PARTS
WHERE PRICE>20
ORDER BY PNO ASC;

SELECT PARTS.PNO,PNAME,SUM(RE)
FROM (SELECT PNAME,PARTS.PNO,QTY*PRICE AS RE
FROM PARTS,ODETAILS
WHERE PARTS.PNO=ODETAILS.PNO)
GROUP BY PARTS.PNO;

SELECT SUM(QTY)
FROM ODETAILS
WHERE PNO=10601;

SELECT ENO
FROM EMPLOYEES
WHERE ZIP =
(SELECT ZIP
FROM ZIPCODES
WHERE CITY='Mumbai');